name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18 # TODO: Pin to tighter version?
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      # TODO: Will these fail as I expect or do I need to put in explicit tests?
      - name: Format
        run: output=$(goimports -d .); echo -n $output; test -z $output
      - name: Build
        run: go vet ./...
      - name: Lint
        run: go vet ./...
      - name: Test
        run: go test ./...
